repo_url: https://github.com/SBD1/2024.1-Undertale
repo_name: 2024.1-Undertale
site_url: https://github.com/SBD1/2024.1-Undertale

site_name: Undertale
nav:
    - Início: "index.md"
    - Apresentações: 
        - Apresentação 1: "apresentacao/modulo1.md"
    - Módulo 1 (Modelagem):
        - Diagrama Entidade Relacionamento: "modulo1/DER.md"
        - Modelo Entidade Relacionamento: "modulo1/MER.md"
        - Dicionário de Dados: "modulo1/DD.md"
        - Modelo Relacional: "modulo1/MR.md"
    - Módulo 2 (SQL):
        - Data Definition Language: "modulo2/DLL.md"
        - Data Manipulation Language: "modulo2/DML.md"
        
theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png
  features:
    - navigation.tabs
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: purple
      toggle:
        icon: material/eye
        name: Mudar para o modo escuro

    # Palette toggle for dark mode
    - scheme: slate
      primary: purple
      toggle:
        icon: material/eye-outline
        name: Mudar para o modo claro